export const routerKey = {
    DASHBOARD: 'DSAHBOARD',
    CUSTOMERS: 'CUSTOMERS',
    SUPPLIERS: 'SUPPLIERS',
    ITEMS: 'ITEMS',
    SALES: 'SALES',
    PURCHASE: 'PURCHASE',
    CASHBOOK: 'CASHBOOK',
    REPORTS: 'REPORTS',
    STAFF: 'STAFF',
    SETTINGS: 'SETTINGS'
}